*** Keywords ***
Test Setup Keyword
    No Operation

Suite Setup Keyword
    No Operation

Test Teardown Keyword
    No Operation

Suite Teardown Keyword
    No Operation

Keyword Setup Keyword
    No Operation

Keyword Teardown Keyword
    No Operation

Amazing Keyword
    [Setup]  Keyword Setup Keyword
    No Operation
    [Teardown]  Keyword Teardown Keyword

Beautiful Keyword
    Amazing Keyword
