*** Keywords ***
Amazing Keyword With Used Return
    RETURN    hello

Beautiful Keyword With Unused Return
    Return From Keyword    hello

Cute Keyword Without Return
    No Operation

Dreamy Keyword With ${embedded_arg} And Used Return
    RETURN    hello

Elegant Keyword With ${embedded_arg} And Unused Return
    RETURN    hello

Fancy Keyword With ${embedded_arg} And No Return
    No Operation
