Output "/app/docs/gif/arguments/arguments.gif"

Set Shell "bash"
Set FontSize 18
Set Width 1000
Set Height 600
Set Padding 20
Set Margin 0
Set CursorBlink false

Hide
    Type "pip install -r requirements.txt --editable /app"
    Enter
    Wait

    Type "clear"
    Enter
Show

Type "robotunused arguments"
Sleep 200ms
Enter
Wait
Sleep 7s

Type "robotunused arguments --show-count"
Sleep 1200ms
Enter
Wait
Sleep 8s
